### ISSUE TITLE
TODO: Populate README.md

### ISSUE THREAD

**Issue by JackGannonUK** [Uquinix/seva-docs#1]
- [ ] Create overview for documentation
- [ ] Create build instructions
- [ ] Add dependency list
- [ ] Create assets
